function [ rpiHead, rpiTrunk, centerData ] = rachSanMarkAnalysis( markData )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%RACHSANMARKANALYSIS Analyze Mark Data from Rachwani-Santamaria paradigm
%   This function calculates mark data analyses and other meta-data from
%   the mark data generated by the Rachwani-Santamaria data collection
%   paradigm.
%
%Author: Wayne Manselle
%Date: November 2014
%
%Inputs:
%   markData -- The Mark Data to Analyze
%
%Outputs:
%   rpiHead -- Whatever RPI stands for, related to the head.
%   rpiTrunk -- RPI data for the Trunk
%   bosData -- Centering data for both the center of base of support and
%              the center point of the trunk
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Prep the Output Variables
rpiHead = zeros(1,3);
rpiTrunk = zeros(1,3);
centerData = zeros(4,9);

%Repeatedly Used Scratch Variable
centerXYZ = zeros(1,3);

%Calculate the RPI Data using data from Mark 3.

%%%%Original Code%%%%
%Initialize transitatory matrices.
tragCenter = zeros(1,3);
vHdCenter = zeros(1,3);
matHdCenter = zeros(3,3);

%Calculate the trageus center by getting the absolute value
%of the difference between the trageus locations.  
%This data is pulled from the X,Y,Z data from sensors 3 and 4.
tragCenter(1)=(markData(3,25) + markData(3,37))/2;
tragCenter(2)=(markData(3,26) + markData(3,38))/2;
tragCenter(3)=(-markData(3,27) + -markData(3,39))/2;

%Subtract the head marker's location from the trageus
%center's location to get the virtual head center.
vHdCenter(1) = tragCenter(1) - markData(3,1);
vHdCenter(2) = tragCenter(2) - markData(3,2);
vHdCenter(3) = tragCenter(3) - -markData(3,3);

%Assemble Matrix of the Head Marker
matHdCenter(1,:) = markData(3,4:6);
matHdCenter(2,:) = markData(3,7:9);
matHdCenter(3,:) = markData(3,10:12);

%Finally, calculate RPI.
rpiHead(:) = matHdCenter' * vHdCenter';

%Marks 5 and 6 are used to determine the center of the base of support as
%positioned on the body.
for mark=1:2
    %Get the Component Data from Sensors 3 and 4
    centerData(mark,1:3) = [markData(7,25) markData(7,26) -markData(7,27)];
    centerData(mark,4:6) = [markData(7,37) markData(7,38) -markData(7,39)];
    %Calculate the Center from the components
    
    centerXYZ(1) = (centerData(mark,1) + centerData(mark,4))/2;
    centerXYZ(2) = (centerData(mark,2) + centerData(mark,5))/2;
    centerXYZ(3) = (centerData(mark,3) + centerData(mark,6))/2;
    %Get the Calculated Center Data
    centerData(mark,7:9) = centerXYZ(:);
end

%Find the midpoint of the midpoints to determine Center of Base of Support
centerData(3,7) = (centerData(1,7) + centerData(2,7))/2;
centerData(3,8) = (centerData(1,8) + centerData(2,8))/2;
centerData(3,9) = (centerData(1,9) + centerData(2,9))/2;

%Mark 7 is used to determine the center of the trunk and its RPI data.

%Get the Component Data. Here we are getting the columns
%corresponding to Sensor 4 and Sensor 2.
centerData(4,1:3) = [markData(7,37) markData(7,38) -markData(7,39)];
centerData(4,4:6) = [markData(7,13) markData(7,14) -markData(7,15)];

%Calculate the Center from the components
centerXYZ(1) = (abs(centerData(4,1) - centerData(4,4))/2)+(min(centerData(4,1),centerData(4,4)));
centerXYZ(2) = (abs(centerData(4,2) - centerData(4,5))/2)+(min(centerData(4,2),centerData(4,5)));
centerXYZ(3) = (abs(centerData(4,3) - centerData(4,6))/2)+(min(centerData(4,3),centerData(4,6)));

%Get the Calculated Center Data
centerData(4,7:9) = centerXYZ(:);

%Subtract the C7 marker's location from the midpoint between C7
%and sternal notch to get the vector.
vTrunk(1) = centerXYZ(1) - markData(7,13);
vTrunk(2) = centerXYZ(2) - markData(7,14);
vTrunk(3) = centerXYZ(3) - -markData(7,15);

%Assemble Rotational Matrix of the C7 Marker
matC7(1,:) = markData(7,16:18);
matC7(2,:) = markData(7,19:21);
matC7(3,:) = markData(7,22:24);

%Finally, calculate RPI_TrunkData.  
rpiTrunk(:) = matC7' * vTrunk';

end